### ISSUE TITLE
v1.10.0 is released before v1.10.0-RC.2

### ISSUE THREAD

**Issue by Nek-** [Sylius/SyliusAdminApiBundle#13]
The version v1.10.0-RC.2 contains modifications (such as PHP 8 support) that are not contained in version 1.10. And the version v1.10.0-RC.2 is released **after** the v1.10.0.

I'm confused, there's probably something wrong with versioning here.

**Comment by Zales0123** [comment]
Thanks for reporting, the only thing I can do is the release of the new [v1.11.0](https://github.com/Sylius/SyliusAdminApiBundle/releases/tag/v1.11.0) 🖖 This will not happen again 🔥

Cheers 🎉
